spring.application.name=notificatin.system

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_system
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Configuration
spring.flyway.url=jdbc:postgresql://localhost:5432/notification_system
spring.flyway.user=user
spring.flyway.password=password
